### ISSUE TITLE
active={active} not working on all menu items

### ISSUE THREAD

**Issue by jakeelwes** [kalambo/hostnation#21]
Seems to underline when on page on, ABOUT US, BEFRIEND & REFER
but not on HOME, REFUGEE or STORIES

https://github.com/kalambo/hostnation/blob/0597bae2897bf376e7ce864b37cb9344998e1f84/src/core/Menu.tsx#L106

**Comment by jsiwhitehead** [comment]
Each page imports and uses a 'Layout' component which has all the general things like the menu, and accepts a location prop which gets passed through to the menu component to tell it which page it is on. This must not be set properly for those pages where this isn't working.
